void separer(char adresse[100], int reseau);
void decoupe(int n, int reseau);
void adresse_reseau(int chiffre1, int chiffre2, int chiffre3, int chiffre4, char bin1[9], char bin2[9], char bin3[9], char bin4[9]);
void decimal(int x, int *chaine);
int binaire(int *tab);
void entrer(char adresse[100]);
void msr(char adresse[100], int reseau, int chiffre1, int chiffre2, int chiffre3, int chiffre4);
void char_int(char *chaine, int tableau[8]);
int bit();
void binaire_inverse(int sous_reseau, int *chaine1);
void ad_broadcast(int chiffre1, int chiffre2, int chiffre3, int chiffre4, int reseau);
void machine(int reseau);
int dec ();